version: "3.8"
services:
  identyquest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: flutter run -d chrome --web-port=5000
